---
permalink: upgrade/verifying-installed-version-of-storagegrid.html 
sidebar: sidebar 
keywords: storagegrid, version, current version, previous version 
summary: Antes de iniciar a atualização, tem de verificar se a versão anterior do StorageGRID está atualmente instalada com a correção disponível mais recente aplicada. 
---
= Verifique a versão instalada do StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de iniciar a atualização, tem de verificar se a versão anterior do StorageGRID está atualmente instalada com a correção disponível mais recente aplicada.

.Sobre esta tarefa
Antes de atualizar para o StorageGRID 11,7, sua grade deve ter o StorageGRID 11,6 instalado. Se você estiver usando uma versão anterior do StorageGRID, você deve instalar todos os arquivos de atualização anteriores juntamente com seus hotfixes mais recentes (fortemente recomendado) até que a versão atual da grade seja StorageGRID 11,6._x.y_.

Um possível caminho de atualização é mostrado no <<Exemplo: Atualize para o StorageGRID 11,6 a partir da versão 11.3.0.8,exemplo>>.


IMPORTANT: O NetApp recomenda vivamente que aplique a correção mais recente para cada versão do StorageGRID antes de atualizar para a próxima versão e que também aplique a correção mais recente para cada nova versão que instalar. Em alguns casos, você deve aplicar um hotfix para evitar o risco de perda de dados. Consulte https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp Downloads: StorageGRID"^] e as notas de versão de cada hotfix para saber mais.

Observe que você pode executar um script para atualizar de 11,3.0,13 ou 11,4.0._y_ em uma etapa e de 11,4.0,7 ou 11,5.0._y_ em uma etapa.  https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_run_combined_major_upgrade_and_hotfix_script_for_StorageGRID["Base de dados de Conhecimento da NetApp: Como executar o script combinado de atualização e correção principal para o StorageGRID"^]Consulte .

.Passos
. Faça login no Gerenciador de Grade usando um link:../admin/web-browser-requirements.html["navegador da web suportado"].
. Na parte superior do Gerenciador de Grade, selecione *Ajuda* > *sobre*.
. Verifique se *Version* é 11,6._x.y_.
+
No número da versão do StorageGRID 11,6._x.y_:

+
** A *versão principal* tem um valor _x_ de 0 (11,6.0).
** Um *hotfix*, se um tiver sido aplicado, tem um valor _y_ (por exemplo, 11,6.0,1).


. Se *Version* não for 11,6._x.y_, aceda a https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp Downloads: StorageGRID"^] para transferir os ficheiros para cada versão anterior, incluindo a correção mais recente para cada versão.
. Obtenha as instruções de atualização para cada versão que você baixou. Em seguida, execute o procedimento de atualização de software para essa versão e aplique o hotfix mais recente para essa versão (altamente recomendado).
+
Consulte link:../maintain/storagegrid-hotfix-procedure.html["Procedimento de correção do StorageGRID"].





== Exemplo: Atualize para o StorageGRID 11,6 a partir da versão 11.3.0.8

O exemplo a seguir mostra as etapas para atualizar do StorageGRID versão 11.3.0.8 para a versão 11,6 em preparação para uma atualização do StorageGRID 11,7.


IMPORTANT: Opcionalmente, você pode executar um script para combinar as etapas 2 e 3 (atualizar de 11,3.0,13 para 11,4.0._y_) e combinar as etapas 4 e 5 (atualizar de 11,4.0,7 para 11,5.0._y_).  https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_run_combined_major_upgrade_and_hotfix_script_for_StorageGRID["Base de dados de Conhecimento da NetApp: Como executar o script combinado de atualização e correção principal para o StorageGRID"^]Consulte .

Transfira e instale o software na seguinte sequência para preparar o seu sistema para a atualização:

. Aplique o hotfix do StorageGRID 11,3.0._y_ mais recente.
. Atualize para a versão principal do StorageGRID 11.4.0.
. Aplique o hotfix do StorageGRID 11,4.0._y_ mais recente.
. Atualize para a versão principal do StorageGRID 11.5.0.
. Aplique o hotfix do StorageGRID 11,5.0._y_ mais recente.
. Atualize para a versão principal do StorageGRID 11.6.0.
. Aplique o hotfix do StorageGRID 11,6.0._y_ mais recente.

