---
permalink: network/appliance-nodes.html 
sidebar: sidebar 
keywords: networking for appliance, port bond mode 
summary: Você pode configurar as portas de rede nos dispositivos StorageGRID para usar os modos de ligação de porta que atendem aos seus requisitos de taxa de transferência, redundância e failover. 
---
= Nós do dispositivo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode configurar as portas de rede nos dispositivos StorageGRID para usar os modos de ligação de porta que atendem aos seus requisitos de taxa de transferência, redundância e failover.

As portas 10/25-GbE nos dispositivos StorageGRID podem ser configuradas no modo de ligação fixa ou agregada para conexões à rede de Grade e à rede do cliente.

As portas de rede de administração de 1 GbE podem ser configuradas no modo Independent (independente) ou ative-Backup (ative-Backup) para conexões à rede de administração.

Consulte as informações sobre os modos de ligação de porta para o seu aparelho:

* link:../installconfig/port-bond-modes-for-sgf6112.html["Modos de ligação de porta (SGF6112)"]
* link:../installconfig/port-bond-modes-for-sg6000-cn-controller.html["Modos de ligação de porta (controlador SG6000-CN)"]
* link:../installconfig/port-bond-modes-for-e5700sg-controller-ports.html["Modos de ligação de porta (controlador E5700SG)"]
* link:../installconfig/port-bond-modes-for-sg100-and-sg1000.html["Modos de ligação de porta (SG100 e SG1000)"]

