---
permalink: admin/grid-management-api-versioning.html 
sidebar: sidebar 
keywords: grid management api, api versioning 
summary: A API de gerenciamento de grade usa o controle de versão para suportar atualizações sem interrupções. 
---
= Controle de versão da API Grid Management
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A API de gerenciamento de grade usa o controle de versão para suportar atualizações sem interrupções.

Por exemplo, este URL de solicitação especifica a versão 3 da API.

`https://_hostname_or_ip_address_/api/v3/authorize`

A versão principal da API de Gerenciamento do Tenant é desfocada quando são feitas alterações que são *_not compatible_* com versões mais antigas. A versão menor da API de Gerenciamento do Tenant é desfocada quando são feitas alterações que *_are compatíveis_* com versões mais antigas. As alterações compatíveis incluem a adição de novos endpoints ou novas propriedades. O exemplo a seguir ilustra como a versão da API é carregada com base no tipo de alterações feitas.

[cols="1a,1a,1a"]
|===
| Tipo de alteração para API | Versão antiga | Nova versão 


 a| 
Compatível com versões mais antigas
 a| 
2,1
 a| 
2,2



 a| 
Não compatível com versões mais antigas
 a| 
2,1
 a| 
3,0

|===
Quando você instala o software StorageGRID pela primeira vez, apenas a versão mais recente da API de gerenciamento de grade está ativada. No entanto, quando você atualiza para uma nova versão de recurso do StorageGRID, você continua tendo acesso à versão mais antiga da API para pelo menos uma versão de recurso do StorageGRID.


NOTE: Você pode usar a API Grid Management para configurar as versões suportadas. Consulte a seção "config" da documentação da API Swagger para obter mais informações. Você deve desativar o suporte para a versão mais antiga depois de atualizar todos os clientes da API Grid Management para usar a versão mais recente.

As solicitações desatualizadas são marcadas como obsoletas das seguintes maneiras:

* O cabeçalho de resposta é "Deprecated: True"
* O corpo de resposta JSON inclui "obsoleto": True
* Um aviso obsoleto é adicionado ao nms.log. Por exemplo:
+
[listing]
----
Received call to deprecated v1 API at POST "/api/v1/authorize"
----




== Determine quais versões de API são suportadas na versão atual

Use a seguinte solicitação de API para retornar uma lista das principais versões da API suportada:

[listing]
----
GET https://{{IP-Address}}/api/versions
{
  "responseTime": "2019-01-10T20:41:00.845Z",
  "status": "success",
  "apiVersion": "3.0",
  "data": [
    2,
    3
  ]
}
----


== Especifique uma versão da API para uma solicitação

Você pode especificar a versão da API usando um parâmetro de caminho (`/api/v3`) ou um cabeçalho (`Api-Version: 3`). Se você fornecer ambos os valores, o valor do cabeçalho substitui o valor do caminho.

[listing]
----
curl https://[IP-Address]/api/v3/grid/accounts

curl -H "Api-Version: 3" https://[IP-Address]/api/grid/accounts
----