---
permalink: admin/manually-triggering-autosupport-message.html 
sidebar: sidebar 
keywords: autosupport, how to send asup message 
summary: Para ajudar o suporte técnico na solução de problemas com o sistema StorageGRID, você pode acionar manualmente uma mensagem AutoSupport a ser enviada. 
---
= Acione manualmente uma mensagem AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para ajudar o suporte técnico na solução de problemas com o sistema StorageGRID, você pode acionar manualmente uma mensagem AutoSupport a ser enviada.

.Antes de começar
* Você deve estar conetado ao Gerenciador de Grade usando um link:../admin/web-browser-requirements.html["navegador da web suportado"].
* Você deve ter a permissão de acesso root ou outra configuração de grade.


.Passos
. Selecione *SUPPORT* > *Tools* > *AutoSupport*.
. Na guia *Configurações*, selecione *Enviar AutoSupport acionado pelo usuário*.
+
O StorageGRID tenta enviar uma mensagem do AutoSupport para o suporte técnico. Se a tentativa for bem-sucedida, os valores *resultado mais recente* e *último tempo bem-sucedido* na guia *resultados* serão atualizados. Se houver um problema, o valor *resultado mais recente* será atualizado para "Falha" e o StorageGRID não tentará enviar a mensagem AutoSupport novamente.

+

NOTE: Depois de enviar uma mensagem AutoSupport acionada pelo usuário, atualize a página AutoSupport no seu navegador após 1 minuto para acessar os resultados mais recentes.


