---
permalink: s3/post-object-restore.html 
sidebar: sidebar 
keywords: post, post object restore, object 
summary: Você pode usar a solicitação de restauração PÓS-objeto S3 para restaurar um objeto armazenado em um pool de storage de nuvem. 
---
= Restauração PÓS-objeto
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar a solicitação de restauração PÓS-objeto S3 para restaurar um objeto armazenado em um pool de storage de nuvem.



== Tipo de solicitação suportada

O StorageGRID suporta apenas solicitações de restauração PÓS-objeto para restaurar um objeto. Não suporta o `SELECT` tipo de restauração. Selecione Requests Return (retornar solicitações `XNotImplemented`).



== Controle de versão

Opcionalmente, especifique `versionId` para restaurar uma versão específica de um objeto em um bucket com versão. Se você não especificar `versionId`, a versão mais recente do objeto será restaurada



== Comportamento da restauração PÓS-objeto em objetos do Cloud Storage Pool

Se um objeto tiver sido armazenado em um pool de armazenamento em nuvem (consulte as instruções para gerenciar objetos com gerenciamento do ciclo de vida das informações), uma solicitação de restauração PÓS-objeto terá o seguinte comportamento, com base no estado do objeto. Consulte "Objeto PRINCIPAL" para obter mais detalhes.


NOTE: Se um objeto for armazenado em um pool de armazenamento em nuvem e uma ou mais cópias do objeto também existirem na grade, não será necessário restaurar o objeto emitindo uma solicitação de restauração PÓS-objeto. Em vez disso, a cópia local pode ser recuperada diretamente, usando uma SOLICITAÇÃO GET Object.

[cols="1a,2a"]
|===
| Estado do objeto | Comportamento da restauração PÓS-objeto 


 a| 
Objeto ingerido no StorageGRID, mas ainda não avaliado pelo ILM, ou objeto não está em um pool de storage de nuvem
 a| 
`403 Forbidden`, `InvalidObjectState`



 a| 
Objeto no Cloud Storage Pool, mas ainda não transicionado para um estado não recuperável
 a| 
`200 OK` Nenhuma alteração é feita.

*Nota*: Antes de um objeto ser transferido para um estado não recuperável, não é possível alterar o seu `expiry-date`.



 a| 
Objeto transicionado para um estado não recuperável
 a| 
`202 Accepted` Restaura uma cópia recuperável do objeto para o pool de armazenamento em nuvem pelo número de dias especificado no corpo da solicitação. No final desse período, o objeto é retornado a um estado não recuperável.

Opcionalmente, use o `Tier` elemento de solicitação para determinar quanto tempo o trabalho de restauração levará para concluir (`Expedited`, `Standard` ou `Bulk` ). Se você não especificar `Tier`, o `Standard` nível será usado.

*Importante*: Se um objeto tiver sido transferido para o S3 Glacier Deep Archive ou se o Cloud Storage Pool usar o armazenamento Azure Blob, não será possível restaurá-lo usando o `Expedited` nível. O seguinte erro é retornado `403 Forbidden`, `InvalidTier`: `Retrieval option is not supported by this storage class`.



 a| 
Objeto em processo de restauração a partir de um estado não recuperável
 a| 
`409 Conflict`, `RestoreAlreadyInProgress`



 a| 
Objeto totalmente restaurado para o Cloud Storage Pool
 a| 
`200 OK`

*Observação:* se um objeto foi restaurado para um estado recuperável, você pode alterar o mesmo `expiry-date` reemitindo a solicitação de restauração PÓS-objeto com um novo valor para `Days`. A data de restauração é atualizada em relação à hora da solicitação.

|===
.Informações relacionadas
link:../ilm/index.html["Gerenciar objetos com ILM"]

link:head-object.html["Objeto HEAD"]

link:s3-operations-tracked-in-audit-logs.html["S3 operações rastreadas em logs de auditoria"]
