---
permalink: maintain/considerations-for-decommissioning-admin-or-gateway-nodes.html 
sidebar: sidebar 
keywords: storagegrid, decommission admin node, decommission gateway node 
summary: Reveja as seguintes considerações antes de desativar um nó de administrador ou um nó de gateway. 
---
= Considerações para desativação do nó de administrador ou do nó de gateway
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Reveja as seguintes considerações antes de desativar um nó de administrador ou um nó de gateway.

* O procedimento de desativação requer acesso exclusivo a alguns recursos do sistema, portanto, você deve confirmar que nenhum outro procedimento de manutenção está sendo executado.
* Não é possível desativar o nó de administração principal.
* Não é possível desativar um nó de administrador ou um nó de gateway se uma de suas interfaces de rede fizer parte de um grupo de alta disponibilidade (HA). Primeiro, é necessário remover as interfaces de rede do grupo HA. Consulte as instruções para link:../admin/managing-high-availability-groups.html["Gerenciamento de grupos de HA"].
* Conforme necessário, você pode alterar com segurança a política de ILM ao desativar um nó de gateway ou um nó de administrador.
* Se você desativar um nó de administrador e o logon único (SSO) estiver ativado para seu sistema StorageGRID, lembre-se de remover a confiança de parte confiável do nó dos Serviços de Federação do ative Directory (AD FS).
* Se utilizar link:../admin/grid-federation-overview.html["federação de grade"]o , certifique-se de que o endereço IP do nó que está a ser desativado não foi especificado para uma ligação de federação de grelha.

