---
permalink: maintain/powering-down-host.html 
sidebar: sidebar 
keywords: storagegrid, recover, stop services, power down host, power off host 
summary: Antes de desligar um host, você deve interromper os serviços em todos os nós da grade nesse host. 
---
= Desligue o host
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de desligar um host, você deve interromper os serviços em todos os nós da grade nesse host.

.Passos
. Faça login no nó da grade:
+
.. Introduza o seguinte comando: `ssh admin@_grid_node_IP_`
.. Introduza a palavra-passe listada no `Passwords.txt` ficheiro.
.. Digite o seguinte comando para mudar para root: `su -`
.. Introduza a palavra-passe listada no `Passwords.txt` ficheiro.


+
Quando você estiver conetado como root, o prompt mudará de `$` para `#`.

. Parar todos os serviços em execução no nó: `service servermanager stop`
+
Os serviços podem levar até 15 minutos para serem encerrados, e você pode querer fazer login no sistema remotamente para monitorar o processo de desligamento.

. Repita as etapas 1 e 2 para cada nó no host.
. Se você tiver um host Linux:
+
.. Faça login no sistema operacional host.
.. Pare o nó: `storagegrid node stop`
.. Encerre o sistema operacional do host.


. Se o nó estiver sendo executado em uma máquina virtual VMware ou se for um nó de dispositivo, execute o comando shutdown: `shutdown -h now`
+
Execute esta etapa independentemente do resultado do `service servermanager stop` comando.

+

NOTE: Depois de emitir o `shutdown -h now` comando em um nó de dispositivo, você deve desligar o dispositivo para reiniciar o nó.

+
Para o aparelho, este comando desliga o controlador, mas o aparelho ainda está ligado. Você deve concluir o próximo passo.

. Se estiver a desligar um nó de dispositivo, siga os passos para o seu aparelho.
+
[role="tabbed-block"]
====
.SGF6112
--
.. Desligue a alimentação do aparelho.
.. Aguarde até que o LED azul de alimentação se desligue.


--
.SG6000
--
.. Aguarde que o LED verde Cache ative na parte de trás dos controladores de armazenamento se desligue.
+
Este LED fica aceso quando os dados em cache precisam ser gravados nas unidades. Tem de esperar que este LED se desligue antes de desligar a alimentação.

.. Desligue o aparelho e aguarde até que o LED azul de alimentação se desligue.


--
.SG5700
--
.. Aguarde que o LED verde Cache ative na parte de trás do controlador de armazenamento seja desligado.
+
Este LED fica aceso quando os dados em cache precisam ser gravados nas unidades. Tem de esperar que este LED se desligue antes de desligar a alimentação.

.. Desligue a alimentação do aparelho e aguarde que todas as atividades de exibição de LED e de sete segmentos parem.


--
.SG100 ou SG1000
--
.. Desligue a alimentação do aparelho.
.. Aguarde até que o LED azul de alimentação se desligue.


--
====
. Faça logout do shell de comando: `exit`


.Informações relacionadas
link:../sg6100/index.html["SGF6112 dispositivos de armazenamento"]

link:../sg6000/index.html["SG6000 dispositivos de armazenamento"]

link:../sg5700/index.html["SG5700 dispositivos de armazenamento"]

link:../sg100-1000/index.html["Aparelhos de serviços SG100 e SG1000"]
