---
permalink: expand/contacting-technical-support.html 
sidebar: sidebar 
keywords: contact technical support 
summary: Se você encontrar erros durante o processo de expansão da grade que você não consegue resolver ou se uma tarefa de grade falhar, entre em Contato com o suporte técnico. 
---
= Entre em Contato com o suporte técnico
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você encontrar erros durante o processo de expansão da grade que você não consegue resolver ou se uma tarefa de grade falhar, entre em Contato com o suporte técnico.

.Sobre esta tarefa
Ao entrar em Contato com o suporte técnico, você deve fornecer os arquivos de log necessários para ajudar a solucionar os erros que você está encontrando.

.Passos
. Conete-se ao nó de expansão que sofreu falhas:
+
.. Introduza o seguinte comando:``ssh -p 8022 admin@_grid_node_IP_``
+

NOTE: A porta 8022 é a porta SSH do sistema operacional base, enquanto a porta 22 é a porta SSH do mecanismo de contentor que executa o StorageGRID.

.. Introduza a palavra-passe listada no `Passwords.txt` ficheiro.
.. Digite o seguinte comando para mudar para root: `su -`
.. Introduza a palavra-passe listada no `Passwords.txt` ficheiro.


+
Depois de iniciar sessão como root, o aviso muda de `$` para `#`.

. Dependendo do estágio em que a instalação chegou, recupere qualquer um dos seguintes logs que estão disponíveis no nó da grade:
+
[cols="1a,2a"]
|===
| Plataforma | Registos 


 a| 
VMware
 a| 
** `/var/log/daemon.log`
** `/var/log/storagegrid/daemon.log`
** `/var/log/storagegrid/nodes/<node-name>.log`




 a| 
Linux
 a| 
** `/var/log/storagegrid/daemon.log`
** `/etc/storagegrid/nodes/<node-name>.conf` (para cada nó com falha)
** `/var/log/storagegrid/nodes/<node-name>.log` (para cada nó com falha; pode não existir)


|===

