---
permalink: ilm/what-storage-pool-is.html 
sidebar: sidebar 
keywords: what is a storage pool 
summary: Um pool de storage é um agrupamento lógico de nós de storage ou nós de arquivamento. 
---
= O que é um pool de storage?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um pool de storage é um agrupamento lógico de nós de storage ou nós de arquivamento.

Quando você instala o StorageGRID, um pool de storage por site é criado automaticamente. Você pode configurar pools de storage adicionais conforme necessário para seus requisitos de storage.

[NOTE]
====
O suporte para nós de arquivamento (tanto para arquivamento na nuvem usando a API S3 como para arquivamento em fita usando middleware TSM) está obsoleto e será removido em uma versão futura. Mover objetos de um nó de arquivamento para um sistema de armazenamento de arquivamento externo foi substituído pelo ILM Cloud Storage Pools, que oferece mais funcionalidade.

link:../ilm/what-cloud-storage-pool-is.html["Use Cloud Storage Pools"]Consulte .

====
Os pools de armazenamento têm dois atributos:

* *Storage grade*: Para nós de storage, o desempenho relativo do armazenamento de backup.
* *Site*: O centro de dados onde os objetos serão armazenados.


Os pools de armazenamento são usados em regras ILM para determinar onde os dados do objeto são armazenados e o tipo de armazenamento usado. Ao configurar regras de ILM para replicação, você seleciona um ou mais pools de storage que incluem nós de storage ou nós de arquivamento. Ao criar perfis de codificação de apagamento, você seleciona um pool de storage que inclui nós de storage.
